preferred_syntax = :sass
http_path = '/'
css_dir = 'src/css'
sass_dir = 'src/sass'
images_dir = 'src/images'
# javascripts_dir = 'assets/javascripts'
relative_assets = true
line_comments = true
# output_style = :compressed
